# Statistical Modeling

## What Predicts if a Flight Will be Delayed?

In [4]:
import pandas as pd
import duckdb as db
import numpy as np
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, classification_report

PATH = "clean_flights.parquet"

In [2]:
con = db.connect()

### Logistic Regression

In [3]:
model_df = con.execute(f"""
SELECT
    CASE 
        WHEN GREATEST(DepDelayMinutes, ArrDelayMinutes) > 15 THEN 1
        ELSE 0
    END AS IsDelayed,

    TaxiOut,
    Distance,
    Month,
    FLOOR(CAST(CRSDepTime AS INTEGER)/100) AS DepHour,
    Reporting_Airline,
    Origin

FROM read_parquet('{PATH}')
USING SAMPLE 200000 ROWS
""").df()

In [5]:
X = model_df.drop("IsDelayed", axis=1)
y = model_df["IsDelayed"]

categorical_cols = ["Reporting_Airline", "Origin"]
numeric_cols = ["TaxiOut", "Distance", "Month", "DepHour"]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", StandardScaler(), numeric_cols),
    ],
    remainder="drop"
)

clf = LogisticRegression(
    solver="saga",
    max_iter=5000,
    n_jobs=-1,
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", clf)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)

probs = model.predict_proba(X_test)[:, 1]
preds = (probs >= 0.5).astype(int)

print("AUC:", roc_auc_score(y_test, probs))
print(classification_report(y_test, preds, digits=3))

/Users/hudsonpifer/CSC369/assignments/assignment1/FinalProject/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

AUC: 0.6802641907360706
              precision    recall  f1-score   support

           0      0.795     0.986     0.880     31133
           1      0.682     0.106     0.184      8867

    accuracy                          0.791     40000
   macro avg      0.738     0.546     0.532     40000
weighted avg      0.770     0.791     0.726     40000

## Logistic Regression with P-Values

### Are Month and Delay independent?

In [6]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

# contingency table
ct = pd.crosstab(model_df["Month"], model_df["IsDelayed"])

chi2, p, dof, expected = chi2_contingency(ct)

n = ct.to_numpy().sum()
k = min(ct.shape)  # min(#rows, #cols)
cramers_v = np.sqrt(chi2 / (n * (k - 1)))

summary = pd.DataFrame({
    "chi2": [chi2],
    "dof": [dof],
    "p_value": [p],
    "cramers_v": [cramers_v],
    "n": [n],
})

display(summary)

# Month to month delay rate:
month_rates = (ct.div(ct.sum(axis=1), axis=0)
                 .rename(columns={0: "pct_not_delayed", 1: "pct_delayed"}))
month_rates["pct_delayed"] = month_rates["pct_delayed"] * 100
month_rates = month_rates[["pct_delayed"]].sort_values("pct_delayed", ascending=False)

display(month_rates)

          chi2  dof        p_value  cramers_v       n
0  1344.636378   11  1.056970e-281   0.081995  200000

IsDelayed  pct_delayed
Month
7            28.890618
6            27.539110
8            23.699196
12           23.393895
5            23.236464
1            21.357444
4            21.034899
3            20.592179
2            20.580865
11           18.284345
10           18.249888
9            17.989166

We strongly reject the null hypothesis that delay status is independent of month due to a p-value of almost 0.

The effect of month on delay probability is statistically significant but modest in magnitude since Cramer's V = 0.082.

### Are Airport and Delay independent?

In [7]:
top_airports = (
    model_df["Origin"]
    .value_counts()
    .head(30)
    .index
)

airport_df = model_df[model_df["Origin"].isin(top_airports)]

ct_airport = pd.crosstab(airport_df["Origin"], airport_df["IsDelayed"])

chi2, p, dof, expected = chi2_contingency(ct_airport)

n = ct_airport.to_numpy().sum()
k = min(ct_airport.shape)
cramers_v = np.sqrt(chi2 / (n * (k - 1)))

pd.DataFrame({
    "chi2": [chi2],
    "dof": [dof],
    "p_value": [p],
    "cramers_v": [cramers_v],
    "n": [n],
})

         chi2  dof        p_value  cramers_v       n
0  623.344661   29  9.184403e-113   0.069357  129582

### Are Airline and Delay Independent?

In [8]:
ct_airline = pd.crosstab(model_df["Reporting_Airline"], model_df["IsDelayed"])

chi2, p, dof, expected = chi2_contingency(ct_airline)

n = ct_airline.to_numpy().sum()
k = min(ct_airline.shape)
cramers_v = np.sqrt(chi2 / (n * (k - 1)))

pd.DataFrame({
    "chi2": [chi2],
    "dof": [dof],
    "p_value": [p],
    "cramers_v": [cramers_v],
    "n": [n],
})

          chi2  dof  p_value  cramers_v       n
0  1730.644956   17      0.0   0.093023  200000

### Are weather presence and sever delay independent?

In [9]:
severity_df = con.execute(f"""
SELECT
    CASE
        WHEN GREATEST(DepDelayMinutes, ArrDelayMinutes) > 180 THEN 1
        ELSE 0
    END AS Severe,

    CASE
        WHEN WeatherDelay > 0 THEN 1
        ELSE 0
    END AS WeatherPresent

FROM read_parquet('{PATH}')
USING SAMPLE 200000 ROWS
""").df()

In [10]:
ct_weather_severe = pd.crosstab(
    severity_df["WeatherPresent"],
    severity_df["Severe"]
)

chi2, p, dof, expected = chi2_contingency(ct_weather_severe)

n = ct_weather_severe.to_numpy().sum()
k = min(ct_weather_severe.shape)
cramers_v = np.sqrt(chi2 / (n * (k - 1)))

pd.DataFrame({
    "chi2": [chi2],
    "dof": [dof],
    "p_value": [p],
    "cramers_v": [cramers_v],
    "n": [n],
})

         chi2  dof  p_value  cramers_v       n
0  2632.74184    1      0.0   0.114733  200000

### Effect Size Summary Table

In [11]:
effect_summary = pd.DataFrame({
    "Factor": [
        "Month → Delay",
        "Airport → Delay",
        "Airline → Delay",
        "Weather Presence → Severe Delay"
    ],
    "Cramers_V": [
        0.081995,   # Month
        0.069357,   # Airport
        0.093023,   # Airline
        0.114733    # Weather → Severe
    ]
}).sort_values("Cramers_V", ascending=False)

def interpret_v(v):
    if v < 0.10:
        return "Small"
    elif v < 0.30:
        return "Moderate"
    else:
        return "Large"

effect_summary["Effect_Size"] = effect_summary["Cramers_V"].apply(interpret_v)

effect_summary

                            Factor  Cramers_V Effect_Size
3  Weather Presence → Severe Delay   0.114733    Moderate
2                  Airline → Delay   0.093023       Small
0                    Month → Delay   0.081995       Small
1                  Airport → Delay   0.069357       Small

## Interaction Effects

In [12]:
model_df_small = con.execute(f"""
SELECT
    CASE 
        WHEN GREATEST(DepDelayMinutes, ArrDelayMinutes) > 15 THEN 1
        ELSE 0
    END AS IsDelayed,

    TaxiOut,
    Distance,
    Month,
    FLOOR(CAST(CRSDepTime AS INTEGER)/100) AS DepHour,
    Reporting_Airline

FROM read_parquet('{PATH}')
USING SAMPLE 200000 ROWS
""").df()

In [13]:
import statsmodels.formula.api as smf

# Treat Month and Airline as categorical
model_df_small["Month"] = model_df_small["Month"].astype("category")
model_df_small["Reporting_Airline"] = model_df_small["Reporting_Airline"].astype("category")

logit_model = smf.logit(
    formula="IsDelayed ~ TaxiOut + Distance + C(Month) + DepHour + C(Reporting_Airline)",
    data=model_df_small
).fit()

print(logit_model.summary())

Optimization terminated successfully.
         Current function value: 0.482244
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              IsDelayed   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199968
Method:                           MLE   Df Model:                           31
Date:                Mon, 09 Mar 2026   Pseudo R-squ.:                 0.08436
Time:                        22:13:41   Log-Likelihood:                -96449.
converged:                       True   LL-Null:                   -1.0533e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -4.3084      0.049    -87.106      0.000      -4.405      -4.211
C(Month)[T.2]                 -0.0810      0.029     -2.789      0.005      -0.138      -0.024
C(Month)[T.3]                  0.0493      0.028      1.778      0.075      -0.005       0.104
C(Month)[T.4]                  0.0909      0.029      3.191      0.001       0.035       0.147
C(Month)[T.5]                  0.1293      0.028      4.601      0.000       0.074       0.184
C(Month)[T.6]                  0.4430      0.027     16.437      0.000       0.390       0.496
C(Month)[T.7]                  0.4497      0.026     16.977      0.000       0.398       0.502
C(Month)[T.8]                  0.2477      0.027      9.171      0.000       0.195       0.301
C(Month)[T.9]                 -0.1573      0.029     -5.426      0.000      -0.214      -0.100
C(Month)[T.10]                -0.1383      0.028     -4.872      0.000      -0.194      -0.083
C(Month)[T.11]                -0.1981      0.029     -6.872      0.000      -0.255      -0.142
C(Month)[T.12]                 0.1717      0.029      5.970      0.000       0.115       0.228
C(Reporting_Airline)[T.AA]     0.7874      0.042     18.559      0.000       0.704       0.871
C(Reporting_Airline)[T.AS]     0.4988      0.051      9.869      0.000       0.400       0.598
C(Reporting_Airline)[T.B6]     0.9781      0.050     19.720      0.000       0.881       1.075
C(Reporting_Airline)[T.DL]     0.4544      0.043     10.594      0.000       0.370       0.538
C(Reporting_Airline)[T.EV]    -0.3409      0.220     -1.553      0.120      -0.771       0.089
C(Reporting_Airline)[T.F9]     1.0577      0.052     20.528      0.000       0.957       1.159
C(Reporting_Airline)[T.G4]     1.1750      0.056     21.119      0.000       1.066       1.284
C(Reporting_Airline)[T.HA]     0.8977      0.069     13.090      0.000       0.763       1.032
C(Reporting_Airline)[T.MQ]     0.5025      0.049     10.220      0.000       0.406       0.599
C(Reporting_Airline)[T.NK]     0.9328      0.050     18.669      0.000       0.835       1.031
C(Reporting_Airline)[T.OH]     0.3128      0.050      6.205      0.000       0.214       0.412
C(Reporting_Airline)[T.OO]     0.3466      0.043      8.050      0.000       0.262       0.431
C(Reporting_Airline)[T.QX]     0.5880      0.091      6.456      0.000       0.410       0.766
C(Reporting_Airline)[T.UA]     0.5238      0.044     11.914      0.000       0.438       0.610
C(Reporting_Airline)[T.WN]     1.1244      0.042     27.080      0.000       1.043       1.206
C(Reporting_Airline)[T.YV]     0.6272      0.068      9.208      0.000       0.494       0.761
C(Reporting_Airline)[T.YX]     0.1221      0.049      2.498      0.012       0.026       0.218
TaxiOut                        0.0600      0.001     90.766      0.000       0.059       0.061
Distance                    5.465e-05   1.03e-05      5.282      0.000    3.44e-05    7.49e-05
DepHour                        0.0849      0.001     71.452      0.000       0.083       0.087
==============================================================================================

After controlling for airline and seasonal effects, departure hour and taxi-out time emerge as the strongest predictors of delay probability. Each additional hour later in the day increases the odds of delay by approximately 9%, while each additional minute of taxi-out increases delay odds by roughly 6%. Airline effects are also substantial, with some carriers exhibiting more than triple the baseline odds of delay.

In [14]:
interaction_model = smf.logit(
    formula="""
    IsDelayed ~ TaxiOut 
               + Distance 
               + C(Month) * DepHour 
               + C(Reporting_Airline)
    """,
    data=model_df_small
).fit()

print(interaction_model.summary())

Optimization terminated successfully.
         Current function value: 0.481663
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              IsDelayed   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199957
Method:                           MLE   Df Model:                           42
Date:                Mon, 09 Mar 2026   Pseudo R-squ.:                 0.08546
Time:                        22:19:33   Log-Likelihood:                -96333.
converged:                       True   LL-Null:                   -1.0533e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -4.0462      0.073    -55.118      0.000      -4.190      -3.902
C(Month)[T.2]                 -0.0229      0.087     -0.262      0.793      -0.194       0.148
C(Month)[T.3]                 -0.0576      0.084     -0.689      0.491      -0.222       0.106
C(Month)[T.4]                 -0.1124      0.086     -1.302      0.193      -0.282       0.057
C(Month)[T.5]                 -0.2181      0.086     -2.535      0.011      -0.387      -0.049
C(Month)[T.6]                 -0.1728      0.083     -2.089      0.037      -0.335      -0.011
C(Month)[T.7]                 -0.2164      0.081     -2.660      0.008      -0.376      -0.057
C(Month)[T.8]                 -0.2534      0.083     -3.043      0.002      -0.417      -0.090
C(Month)[T.9]                 -0.4372      0.090     -4.864      0.000      -0.613      -0.261
C(Month)[T.10]                -0.2766      0.087     -3.194      0.001      -0.446      -0.107
C(Month)[T.11]                -0.1312      0.087     -1.516      0.129      -0.301       0.038
C(Month)[T.12]                 0.1352      0.086      1.566      0.117      -0.034       0.304
C(Reporting_Airline)[T.AA]     0.7883      0.042     18.572      0.000       0.705       0.872
C(Reporting_Airline)[T.AS]     0.4971      0.051      9.826      0.000       0.398       0.596
C(Reporting_Airline)[T.B6]     0.9797      0.050     19.745      0.000       0.882       1.077
C(Reporting_Airline)[T.DL]     0.4527      0.043     10.551      0.000       0.369       0.537
C(Reporting_Airline)[T.EV]    -0.3369      0.219     -1.536      0.125      -0.767       0.093
C(Reporting_Airline)[T.F9]     1.0598      0.052     20.550      0.000       0.959       1.161
C(Reporting_Airline)[T.G4]     1.1738      0.056     21.077      0.000       1.065       1.283
C(Reporting_Airline)[T.HA]     0.8970      0.069     13.076      0.000       0.763       1.031
C(Reporting_Airline)[T.MQ]     0.4998      0.049     10.157      0.000       0.403       0.596
C(Reporting_Airline)[T.NK]     0.9334      0.050     18.664      0.000       0.835       1.031
C(Reporting_Airline)[T.OH]     0.3164      0.050      6.273      0.000       0.218       0.415
C(Reporting_Airline)[T.OO]     0.3470      0.043      8.056      0.000       0.263       0.431
C(Reporting_Airline)[T.QX]     0.5807      0.091      6.369      0.000       0.402       0.759
C(Reporting_Airline)[T.UA]     0.5235      0.044     11.903      0.000       0.437       0.610
C(Reporting_Airline)[T.WN]     1.1223      0.042     27.015      0.000       1.041       1.204
C(Reporting_Airline)[T.YV]     0.6299      0.068      9.243      0.000       0.496       0.763
C(Reporting_Airline)[T.YX]     0.1236      0.049      2.527      0.011       0.028       0.220
TaxiOut                        0.0596      0.001     90.079      0.000       0.058       0.061
Distance                    5.575e-05   1.04e-05      5.380      0.000    3.54e-05    7.61e-05
DepHour                        0.0665      0.004     16.155      0.000       0.058       0.075
C(Month)[T.2]:DepHour         -0.0041      0.006     -0.686      0.493      -0.016       0.008
C(Month)[T.3]:DepHour          0.0079      0.006      1.378      0.168      -0.003       0.019
C(Month)[T.4]:DepHour          0.0147      0.006      2.507      0.012       0.003       0.026
C(Month)[T.5]:DepHour          0.0250      0.006      4.275      0.000       0.014       0.036
C(Month)[T.6]:DepHour          0.0442      0.006      7.853      0.000       0.033       0.055
C(Month)[T.7]:DepHour          0.0479      0.006      8.639      0.000       0.037       0.059
C(Month)[T.8]:DepHour          0.0359      0.006      6.349      0.000       0.025       0.047
C(Month)[T.9]:DepHour          0.0202      0.006      3.313      0.001       0.008       0.032
C(Month)[T.10]:DepHour         0.0102      0.006      1.719      0.086      -0.001       0.022
C(Month)[T.11]:DepHour        -0.0046      0.006     -0.775      0.438      -0.016       0.007
C(Month)[T.12]:DepHour         0.0027      0.006      0.460      0.645      -0.009       0.014
==============================================================================================

The impact of departure hour on delay probability is significantly stronger during summer months. For example, in July the marginal effect of departure hour nearly doubles relative to baseline months, indicating that delay accumulation is seasonally amplified.

In [15]:
interaction_model2 = smf.logit(
    formula="""
    IsDelayed ~ Distance 
               + C(Month) * TaxiOut
               + DepHour 
               + C(Reporting_Airline)
    """,
    data=model_df_small
).fit()

print(interaction_model2.summary())

Optimization terminated successfully.
         Current function value: 0.482088
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              IsDelayed   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199957
Method:                           MLE   Df Model:                           42
Date:                Mon, 09 Mar 2026   Pseudo R-squ.:                 0.08465
Time:                        22:46:51   Log-Likelihood:                -96418.
converged:                       True   LL-Null:                   -1.0533e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -4.3811      0.061    -71.944      0.000      -4.500      -4.262
C(Month)[T.2]                 -0.1855      0.062     -2.969      0.003      -0.308      -0.063
C(Month)[T.3]                  0.0578      0.060      0.967      0.334      -0.059       0.175
C(Month)[T.4]                  0.1892      0.062      3.047      0.002       0.067       0.311
C(Month)[T.5]                  0.2357      0.061      3.847      0.000       0.116       0.356
C(Month)[T.6]                  0.6114      0.059     10.419      0.000       0.496       0.726
C(Month)[T.7]                  0.5190      0.058      9.001      0.000       0.406       0.632
C(Month)[T.8]                  0.3780      0.059      6.457      0.000       0.263       0.493
C(Month)[T.9]                 -0.0624      0.063     -0.988      0.323      -0.186       0.061
C(Month)[T.10]                 0.0608      0.062      0.986      0.324      -0.060       0.182
C(Month)[T.11]                -0.2715      0.063     -4.333      0.000      -0.394      -0.149
C(Month)[T.12]                 0.3233      0.062      5.225      0.000       0.202       0.445
C(Reporting_Airline)[T.AA]     0.7877      0.042     18.565      0.000       0.705       0.871
C(Reporting_Airline)[T.AS]     0.4993      0.051      9.877      0.000       0.400       0.598
C(Reporting_Airline)[T.B6]     0.9787      0.050     19.732      0.000       0.881       1.076
C(Reporting_Airline)[T.DL]     0.4530      0.043     10.563      0.000       0.369       0.537
C(Reporting_Airline)[T.EV]    -0.3738      0.221     -1.691      0.091      -0.807       0.059
C(Reporting_Airline)[T.F9]     1.0580      0.052     20.532      0.000       0.957       1.159
C(Reporting_Airline)[T.G4]     1.1729      0.056     21.073      0.000       1.064       1.282
C(Reporting_Airline)[T.HA]     0.8967      0.069     13.069      0.000       0.762       1.031
C(Reporting_Airline)[T.MQ]     0.5016      0.049     10.201      0.000       0.405       0.598
C(Reporting_Airline)[T.NK]     0.9326      0.050     18.664      0.000       0.835       1.031
C(Reporting_Airline)[T.OH]     0.3156      0.050      6.261      0.000       0.217       0.414
C(Reporting_Airline)[T.OO]     0.3464      0.043      8.044      0.000       0.262       0.431
C(Reporting_Airline)[T.QX]     0.5844      0.091      6.416      0.000       0.406       0.763
C(Reporting_Airline)[T.UA]     0.5248      0.044     11.936      0.000       0.439       0.611
C(Reporting_Airline)[T.WN]     1.1224      0.042     27.030      0.000       1.041       1.204
C(Reporting_Airline)[T.YV]     0.6256      0.068      9.181      0.000       0.492       0.759
C(Reporting_Airline)[T.YX]     0.1225      0.049      2.505      0.012       0.027       0.218
Distance                    5.546e-05   1.03e-05      5.359      0.000    3.52e-05    7.57e-05
TaxiOut                        0.0635      0.002     33.336      0.000       0.060       0.067
C(Month)[T.2]:TaxiOut          0.0055      0.003      1.934      0.053   -7.47e-05       0.011
C(Month)[T.3]:TaxiOut         -0.0002      0.003     -0.075      0.941      -0.006       0.005
C(Month)[T.4]:TaxiOut         -0.0052      0.003     -1.741      0.082      -0.011       0.001
C(Month)[T.5]:TaxiOut         -0.0057      0.003     -1.918      0.055      -0.011       0.000
C(Month)[T.6]:TaxiOut         -0.0093      0.003     -3.260      0.001      -0.015      -0.004
C(Month)[T.7]:TaxiOut         -0.0036      0.003     -1.284      0.199      -0.009       0.002
C(Month)[T.8]:TaxiOut         -0.0070      0.003     -2.503      0.012      -0.012      -0.002
C(Month)[T.9]:TaxiOut         -0.0050      0.003     -1.661      0.097      -0.011       0.001
C(Month)[T.10]:TaxiOut        -0.0107      0.003     -3.658      0.000      -0.016      -0.005
C(Month)[T.11]:TaxiOut         0.0040      0.003      1.382      0.167      -0.002       0.010
C(Month)[T.12]:TaxiOut        -0.0080      0.003     -2.767      0.006      -0.014      -0.002
DepHour                        0.0852      0.001     71.623      0.000       0.083       0.088
==============================================================================================

In [17]:
model_df_small = con.execute(f"""
SELECT
    CASE 
        WHEN GREATEST(DepDelayMinutes, ArrDelayMinutes) > 15 THEN 1
        ELSE 0
    END AS IsDelayed,

    CASE 
        WHEN WeatherDelay > 0 THEN 1
        ELSE 0
    END AS WeatherPresent,

    TaxiOut,
    Distance,
    Month,
    FLOOR(CAST(CRSDepTime AS INTEGER)/100) AS DepHour,
    Reporting_Airline,
    Origin

FROM read_parquet('{PATH}')
USING SAMPLE 200000 ROWS
""").df()

In [18]:
top_airports = (
    model_df_small["Origin"]
    .value_counts()
    .head(20)
    .index
)

model_df_small["LargeHub"] = (
    model_df_small["Origin"].isin(top_airports)
).astype(int)

In [19]:
import statsmodels.formula.api as smf

interaction_model3 = smf.logit(
    formula="""
    IsDelayed ~ TaxiOut
               + Distance
               + DepHour
               + WeatherPresent * LargeHub
               + C(Month)
               + C(Reporting_Airline)
    """,
    data=model_df_small
).fit()

print(interaction_model3.summary())

Optimization terminated successfully.
         Current function value: 0.466475
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:              IsDelayed   No. Observations:               200000
Model:                          Logit   Df Residuals:                   199965
Method:                           MLE   Df Model:                           34
Date:                Mon, 09 Mar 2026   Pseudo R-squ.:                  0.1154
Time:                        22:49:43   Log-Likelihood:                -93295.
converged:                       True   LL-Null:                   -1.0547e+05
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -4.3289      0.051    -84.818      0.000      -4.429      -4.229
C(Month)[T.2]                 -0.0457      0.030     -1.537      0.124      -0.104       0.013
C(Month)[T.3]                  0.0297      0.028      1.043      0.297      -0.026       0.085
C(Month)[T.4]                  0.0576      0.029      1.960      0.050   -3.75e-06       0.115
C(Month)[T.5]                  0.1346      0.029      4.656      0.000       0.078       0.191
C(Month)[T.6]                  0.4126      0.028     14.868      0.000       0.358       0.467
C(Month)[T.7]                  0.4607      0.027     16.899      0.000       0.407       0.514
C(Month)[T.8]                  0.2493      0.028      8.962      0.000       0.195       0.304
C(Month)[T.9]                 -0.1651      0.030     -5.562      0.000      -0.223      -0.107
C(Month)[T.10]                -0.1000      0.029     -3.457      0.001      -0.157      -0.043
C(Month)[T.11]                -0.1544      0.030     -5.230      0.000      -0.212      -0.097
C(Month)[T.12]                 0.1801      0.029      6.112      0.000       0.122       0.238
C(Reporting_Airline)[T.AA]     0.7705      0.044     17.534      0.000       0.684       0.857
C(Reporting_Airline)[T.AS]     0.5193      0.052     10.000      0.000       0.418       0.621
C(Reporting_Airline)[T.B6]     1.0599      0.050     21.025      0.000       0.961       1.159
C(Reporting_Airline)[T.DL]     0.4705      0.044     10.612      0.000       0.384       0.557
C(Reporting_Airline)[T.EV]    -0.0239      0.191     -0.125      0.900      -0.398       0.350
C(Reporting_Airline)[T.F9]     1.0817      0.053     20.381      0.000       0.978       1.186
C(Reporting_Airline)[T.G4]     1.0549      0.057     18.370      0.000       0.942       1.167
C(Reporting_Airline)[T.HA]     0.8701      0.070     12.407      0.000       0.733       1.008
C(Reporting_Airline)[T.MQ]     0.3641      0.051      7.076      0.000       0.263       0.465
C(Reporting_Airline)[T.NK]     0.9501      0.051     18.583      0.000       0.850       1.050
C(Reporting_Airline)[T.OH]     0.3442      0.052      6.632      0.000       0.242       0.446
C(Reporting_Airline)[T.OO]     0.2450      0.045      5.474      0.000       0.157       0.333
C(Reporting_Airline)[T.QX]     0.4938      0.094      5.241      0.000       0.309       0.678
C(Reporting_Airline)[T.UA]     0.5168      0.045     11.371      0.000       0.428       0.606
C(Reporting_Airline)[T.WN]     1.1305      0.043     26.299      0.000       1.046       1.215
C(Reporting_Airline)[T.YV]     0.4143      0.072      5.741      0.000       0.273       0.556
C(Reporting_Airline)[T.YX]     0.0920      0.050      1.825      0.068      -0.007       0.191
TaxiOut                        0.0596      0.001     87.257      0.000       0.058       0.061
Distance                    6.426e-05   1.05e-05      6.130      0.000    4.37e-05    8.48e-05
DepHour                        0.0880      0.001     72.246      0.000       0.086       0.090
WeatherPresent                 6.2234      0.336     18.528      0.000       5.565       6.882
LargeHub                      -0.1106      0.013     -8.804      0.000      -0.135      -0.086
WeatherPresent:LargeHub        0.6306      0.604      1.045      0.296      -0.552       1.814
==============================================================================================